### ISSUE TITLE
Save results of body measurement.

### ISSUE THREAD

**Issue by chenyangcheung** [chenyangcheung/QinchuanCattleBMS#21]
Cut two-dimensional picture and three-dimensional *.pcd file and paste them into another file with the results of body measurement.

**Comment by Fibird** [comment]
@chenyangcheung Cut? What do you mean? Can you describe it in detail?

**Comment by chenyangcheung** [comment]
@Fibird I mean we can put results of BMS(7 value of traits) and the corresponding 2D picture and 3d *.pcd into one folder. (cut, copy,paste)

**Comment by Fibird** [comment]
@chenyangcheung Got it!
