### ISSUE TITLE
The picture comes from "Open Video" won't be undistorted.

### ISSUE THREAD

**Issue by chenyangcheung** [chenyangcheung/QinchuanCattleBMS#22]
Since pictures captured by our camera has been undistorted it won't be needed when we re-compute it.

**Comment by Fibird** [comment]
I can't figure it out. Can you describe it in detail?

**Comment by chenyangcheung** [comment]
It‘s okay, we've completed main functions. This enhancement won't be necessary.

**Comment by Fibird** [comment]
Alright!
